
data class AppStrings(
    val langTitle: String,
    val cancel: String,
    val changeTheme: String,
    val dataAndHistory: String,
    val clearData: String,


    val statusError: String,
    val statusInvalid: String,
    val statusSsl: String,
    val statusHttp: String,
    val statusNoServer: String,
    val cookiesEmpty: String,
    val inspectorTitle: String,
    val btnOpenBrowserEmoji: String,
    val searchLogPlaceholder: String,
    val searchTooBig: String,
    val searchError: String,
    val notFound: String,
    val ignoresslerrors: String,
    val self_signed_certificates: String,
    val checkssl: String,
    val strictcertificateverification: String,
    val securityandssl: String,
    val requesttimeout: String,
    val auto_redirect: String,
    val network_and_connectivity: String,
    val application_settings: String,
    val ready_settings: String,
    val clear_history_and_input: String,
    val data_and_history: String,
    val change_the_design_theme: String,
    val registration: String,
    val default: String,
    val user_agent: String,
    val cancel_theme: String,
    val theme_dark: String,
    val theme_light: String,
    val theme_system: String,
    val select_theme_topic: String,
    val searchLoading: String,
    val findMatches: String,
    val sites_found: String,
    val example_keyword: String,
    val searches_matches: String,
    val story_searches: String,
    val analysis_scan: String,
    val run_scan: String,
    val check_scan: String,
    val scan_settings: String,
    val inspector_scan: String,
    val story_scan: String,
    val ready_info: String,
    val privacy_policy_info: String,
    val document_info: String,
    val github_info: String,
    val github_info_info: String,
    val source_code_info: String,
    val dev_info: String,
    val version_info: String,
    val download_info:String,
    val app_info: String,
    val home_info: String,
    val home_settings: String,
    val home_site: String,
    val ready_history: String,
    val history_empty: String,
    val clear_history: String,
    val history_scan: String,
    val common_redirect: String,
)


private val russianStrings = AppStrings(
    langTitle = "Выбор языка",
    cancel = "Отмена",
    changeTheme = "Сменить тему оформления",
    dataAndHistory = "Данные и история",
    clearData = "Очистить данные",
    statusError = "Ошибка",
    statusInvalid = "Неверный ввод",
    statusSsl = "Https безопасно",
    statusHttp = "Http небезопасно",
    statusNoServer = "Сервер недоступен",
    cookiesEmpty = "Куки не найдены",
    inspectorTitle = "Данные ответа сервера",
    btnOpenBrowserEmoji = "Открыть сайт в браузере",
    searchLogPlaceholder = "Поиск текста в логе...",
    searchTooBig = "Ошибка: Лог слишком большой",
    searchError = "Ошибка поиска",
    notFound = "Ничего не найдено",
    ignoresslerrors = "Игнорировать ошибки SSL",
    self_signed_certificates = "(самоподписанные сертификаты)",
    checkssl = "Проверять SSL",
    strictcertificateverification = "(строгая проверка сертификатов)",
    securityandssl = "Безопасность и SSL",
    requesttimeout = "Тайм-аут запросы:",
    auto_redirect = "Авто-редирект",
    network_and_connectivity = "Сеть и подключение",
    application_settings = "Настройки приложения",
    ready_settings = "Готово",
    clear_history_and_input = "Очистить историю и ввод",
    data_and_history = "Дата и история",
    change_the_design_theme = "Изменить тему оформления",
    registration = "Регистрация",
    default = "По умолчанию",
    user_agent = "Пользовательский Агент",
    cancel_theme = "Отмена",
    theme_dark = "Тёмный",
    theme_light = "Светлый",
    theme_system = "Как в системе",
    select_theme_topic = "Выберите тему",
    "Поиск...",
     findMatches = "Найти совпадения",
    sites_found = "Найденые сайты",
    example_keyword = "Введите ключевое слово (например, example)",
    searches_matches = "Поиск по совпадениям",
    story_searches = "История",
    analysis_scan = "Анализ",
    run_scan = "Запустить скан",
    check_scan = "Проверить URL",
    scan_settings = "Настройки",
    inspector_scan = "Ответ",
    story_scan = "История",
    ready_info = "Готово",
    privacy_policy_info = "Политика конфиденциальности ↗",
    document_info = "Документация",
    github_info = "Проект репозитория на GitHub ↗",
    github_info_info = "GitHub",
    source_code_info = "Исходный код и разработка",
    dev_info = "Разработчик: Георгий Смердов",
    version_info = "Версия:",
    download_info = "Скачано: GitHub",
    app_info = "Информация о приложении",
    home_info = "Информация",
    home_settings =  "Настройки",
    home_site = "Сайт разработчика",
    ready_history = "Готово",
    history_empty = "История проверок пуста.",
    clear_history = "Очистить",
    history_scan = "История скана",
    common_redirect = "Следовать перенаправлениям сайтов"
)


private val englishStrings = AppStrings(
    langTitle = "Select Language",
    cancel = "Cancel",
    changeTheme = "Change the design theme",
    dataAndHistory = "Data and history",
    clearData = "Clear data",
    statusError = "Error",
    statusInvalid = "Invalid input",
    statusSsl = "Https secure",
    statusHttp = "Http insecure",
    statusNoServer = "Server unreachable",
    cookiesEmpty = "No cookies found",
    inspectorTitle = "Server response data",
    btnOpenBrowserEmoji = "Open site in browser",
    searchLogPlaceholder = "Search text inside log...",
    searchTooBig = "Error: Log is too large",
    searchError = "error",
    notFound = "Nothing found",
    ignoresslerrors = "Ignore SSL errors",
    self_signed_certificates = "(self-signed certificates)",
    checkssl = "Check SSL",
    strictcertificateverification = "(strict certificate verification)",
    securityandssl = "Security and SSL",
    requesttimeout = "Request timeout:",
    auto_redirect = "Auto-redirect",
    network_and_connectivity = "Network and Connectivity",
    application_settings = "Application settings",
    ready_settings = "Ready",
    clear_history_and_input = "Clear history and input",
    data_and_history = "Data and history",
    change_the_design_theme = "Change the design theme",
    registration = "Registration",
    default = "Default",
    user_agent = "User-Agent",
    cancel_theme = "Cancel",
    theme_dark = "Dark",
    theme_light = "Light",
    theme_system = "An in the system",
    select_theme_topic = "Select a topic",
    "Search...",
    findMatches = "Find matches",
    sites_found = "Sites found",
    example_keyword = "Enter a keyword (e.g. example)",
    searches_matches = "Searches by matches",
    story_searches = "Story",
    analysis_scan = "Analysis",
    run_scan = "Run scan",
    check_scan = "Check URL",
    scan_settings = "Settings",
    inspector_scan = "Answer",
    story_scan = "Story",
    ready_info = "Ready",
    privacy_policy_info = "Privacy policy ↗",
    document_info = "Documentation",
    github_info = "Project repository on GitHub ↗",
    github_info_info = "GitHub",
    source_code_info = "Source code and development",
    dev_info = "Developer: Georgy Smerdov",
    version_info = "Version:",
    download_info = "Downloaded: GitHub",
    app_info = "Application information",
    home_info = "Information",
    home_settings = "Settings",
    home_site = "Developer's website",
    ready_history = "Ready",
    history_empty = "The check history is empty",
    clear_history = "Clear",
    history_scan = "Scan history",
    common_redirect = "Follow site redirects"



)

fun getStringsForLanguage(lang: String): AppStrings {
    return when (lang) {
        "en" -> englishStrings
        else -> russianStrings
    }
}
